In [0]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [0]:
steps = [("standard_scaler", StandardScaler()), ("classifier", LogisticRegression())]


In [0]:
 steps
 [('standard_scaler', StandardScaler()), ('classifier', 
LogisticRegression())]
 pipe=Pipeline(steps)

In [0]:
 from sklearn import set_config
 set_config(display="diagram")
 pipe
 Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [0]:
 from sklearn.datasets import make_classification
 X,y=make_classification(n_samples=1000)

In [0]:
 X.shape

(1000, 20)

In [0]:
 from sklearn.model_selection import train_test_split
 X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [0]:
X_train

array([[-0.01661629,  0.01651883,  0.0470543 , ...,  0.60408578,
        -0.00992514,  0.56764708],
       [ 0.39889024, -2.18959143, -0.45134479, ...,  1.50910428,
        -0.06643286,  0.15784563],
       [-2.51939343, -1.89852001, -1.09229424, ...,  0.34808525,
        -1.88682459,  0.20259422],
       ...,
       [-2.43535446, -0.30469711, -1.68956658, ..., -1.12563263,
        -1.32809088,  0.71258427],
       [-1.33160358, -0.09344106, -0.31054279, ..., -0.73738533,
        -0.86899721, -0.76131105],
       [ 0.5350744 ,  0.86850235, -0.23056471, ...,  0.98992278,
        -0.05462289,  2.39110038]])

In [0]:
pipe.fit(X_train,y_train)
Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])
y_pred=pipe.predict(X_test)
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,

In [0]:
 from sklearn.decomposition import PCA
 from sklearn.svm import SVC

In [0]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]
pipe2=Pipeline(steps)
pipe2.fit(X_train,y_train)
Pipeline(steps=[('scaling', StandardScaler()), ('PCA', 
PCA(n_components=3)),
                ('SVC', SVC())])
pipe2.predict(X_test)

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,

In [0]:
 from sklearn.impute import SimpleImputer

In [0]:
import numpy as np
numeric_processor=Pipeline(
    
steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy
 ="mean")),
          ("scaler",StandardScaler())]
 )
numeric_processor
Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [0]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    
steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehot",OneHotEncoder(handle_unknown="ignore"))]
 )
categorical_processor
Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', 
strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [0]:
 from sklearn.compose import ColumnTransformer
 preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","City"]),
    ("numerical",numeric_processor,["age","height"])]
 )

In [0]:
preprocessor
ColumnTransformer(transformers=[('categorical',
                                 
Pipeline(steps=[('imputation_consatnt',
                                                  
SimpleImputer(fill_value='missing',
                                                                
strategy='constant')),
                                                 ('onehot',
                                                  
OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', 
StandardScaler())]),
                                 ['age', 'height'])])

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [0]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe
Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  
Pipeline(steps=[('imputation_consatnt',
                                                                   
SimpleImputer(fill_value='missing',
                                                                       
strategy='constant')),
                                                                  
('onehot',
                                                                   
OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  
Pipeline(steps=[('imputation_mean',
                                                                   
SimpleImputer()),
                                                                  
('scaler',
                                                                   
StandardScaler())]),
                                                  ['age', 
'height'])])),
                ('logisticregression', LogisticRegression())])

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])